### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by ghost** [AT-PHPIntership/borrow-book#30]
## List Function
**1.User**        
- [x] Profile 
    - [x] login, logout
    - [x]  register
     - [x] update profile
- [x] Library 
    - [x] Show book new
     - [x] View list of all book
     - [x] Show detail book
     - [x] Search book by filters category
     - [x] Search book by filters rate
     - [x] Search book by filters language
     - [x] Search book by filters number of page
     - [x] Search book in text field
- [x] Post    
     - [x] Add post
     - [x] Update post
     - [x] Delete post
     - [x] Add rate
     - [x] Update rate
 - [x] Borrowes    
     - [x] Show list borrow book of me
 - [x] Favorite    
     - [x] Mark favorite

**2.Admin**       
 - [x] Manage user     
     - [x] View user
     - [x] Delete user
     - [x] Add user
     - [x] Update user
     - [x] Search User
 - [x] Manage Book 
    - [x] Show book
    - [x] Add book
    - [x] Update book
    - [x] Delete book
    - [x] Search book
 - [x] Manage Borrow   
     - [x] Show list user borrow book
 - [x] Manage post 
     - [x] Show post
     - [x] Delete post
 - [x] Manage favorite 
     - [x] Show all user favorite with book
 - [x] Statistical
